name: Wake Up Railway Service

on:
  schedule:
    # cron 是 UTC 时间,下面示例是每天北京时间 8:00 和 20:00(即 UTC 0:00 和 12:00)
    - cron: '55 19 * * *'
    - cron: '00 20 * * *'
    # - cron: '0 12 * * *'
  workflow_dispatch:  # 可选,允许你手动在 GitHub 页面点击触发,方便测试

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service to wake it up
        run: |
          curl -sS -o /dev/null -w "HTTP status: %{http_code}\n" https://bemby-production-1862.up.railway.app
